# Copy this file to config/local_cfg.yaml and replace the example paths.
# MIT-BIH 原始資料的路徑
#ECG_corpus_dir: /home/taes10056/mit-bih-nsrdb
ECG_corpus_dir: /home/taes10056/mit-bih-nsrdb/mit-bih-normal-sinus-rhythm-database-1.0.0
# 處理後的心電圖存放路徑 (維持預設或指定到專案內)
ECG_storage_dir: /home/taes10056/SSEMG-Net/processed/ecg

# NinaPro DB2 原始資料的路徑
EMG_corpus_dir: /home/taes10056/EMG_DB2
# 最終混合完成的 sEMG 資料集存放路徑 (維持預設的相對路徑即可)
sEMG_dataset_dir: semg_data/processed